[package]
name = "fractals"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "fractals"
path = "native/fractals/src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
crossbeam = "0.8.4"
image = "0.25.4"
num = "0.4.3"
num_cpus = "1.16.0"
rustler = "0.34.0"
